# Generated by Django 5.2.3 on 2025-06-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='programmes/heroes/'),
        ),
        migrations.AddField(
            model_name='programme',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='programme',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='programme',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='programmes/videos/'),
        ),
    ]
