# Generated by Django 5.2.3 on 2025-06-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_prerequisiteprogrammes_programme_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='programmes', to='courses.prerequisiteprogrammes'),
        ),
    ]
