# Generated by Django 5.2.3 on 2025-06-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_programme_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the unit in the context of the programme.'),
        ),
        migrations.AddField(
            model_name='programmeunit',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the unit in the context of the programme.'),
        ),
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, help_text='Description of the unit in the context of the programme.'),
        ),
    ]
