# Generated by Django 5.2.3 on 2025-06-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_codesubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='codesubmission',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
    ]
