# Generated by Django 5.2.3 on 2025-06-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_codesubmission_error_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codechallenge',
            old_name='sample_input',
            new_name='starter_code',
        ),
        migrations.RemoveField(
            model_name='codechallenge',
            name='test_file',
        ),
        migrations.AddField(
            model_name='codechallenge',
            name='test_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
